### ISSUE TITLE
Refresh frequency with Import

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#1616]
This page states that "Models with Imported data can be refreshed at most once per hour", but this is not accurate as dataset refreshes can be done within smaller intervals, depending on whether you have Pro or Premium, and what you use to trigger the refreshes (Power BI service UI, PowerShell/API, or Power Automate).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @otravers . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
You're right - thanks for that clarification. We've updated the docs to reflect. Thanks!

**Comment by otravers** [comment]
@davidiseminger Maybe the pages are cached on the server and take a while to refresh? I still see: 

"Models with imported data can be refreshed _at most once per hour_. **Tf** the data is continually changing"

Also note the typo I highlighted in bold.
